[tool.poetry]
name = "opalescence"
version = "0.1.0"
description = ""
authors = ["brian houston morrow <killerbat00@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9.1"
aiohttp = "^3.7.4"
bitstring = "^3.1.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
